//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IContainsCounterService")]
public interface IContainsCounterService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContainsCounterService/ContainsCounter", ReplyAction="http://tempuri.org/IContainsCounterService/ContainsCounterResponse")]
    int ContainsCounter(string first, string second);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContainsCounterService/ContainsCounter", ReplyAction="http://tempuri.org/IContainsCounterService/ContainsCounterResponse")]
    System.Threading.Tasks.Task<int> ContainsCounterAsync(string first, string second);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IContainsCounterServiceChannel : IContainsCounterService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ContainsCounterServiceClient : System.ServiceModel.ClientBase<IContainsCounterService>, IContainsCounterService
{
    
    public ContainsCounterServiceClient()
    {
    }
    
    public ContainsCounterServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ContainsCounterServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ContainsCounterServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ContainsCounterServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public int ContainsCounter(string first, string second)
    {
        return base.Channel.ContainsCounter(first, second);
    }
    
    public System.Threading.Tasks.Task<int> ContainsCounterAsync(string first, string second)
    {
        return base.Channel.ContainsCounterAsync(first, second);
    }
}
